// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_x_2Im00ms_4p3Okrbb9nuBUYihgL4c',
    appId: '1:5500525258:android:c69656cbd142fe8c17b233',
    messagingSenderId: '5500525258',
    projectId: 'best-note-505bb',
    storageBucket: 'best-note-505bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgTM5QsZF7ZM3Gxv2z3tmy6kN1DDNP8kQ',
    appId: '1:5500525258:ios:889dea94e2a1effb17b233',
    messagingSenderId: '5500525258',
    projectId: 'best-note-505bb',
    storageBucket: 'best-note-505bb.appspot.com',
    androidClientId: '5500525258-7likfbqgaa0cppj8lf5rebgkem42ant0.apps.googleusercontent.com',
    iosClientId: '5500525258-62q5edr7mhgoh5tarehbot6k7074k952.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestNote',
  );
}
